version: '3.7'
services:


  mysql:
    image: mysql:8.0

    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql_1
      - MYSQL_USER=adm
      - MYSQL_PASSWORD=pass

